[tool.poetry]
name = "k-boys-hackathon"
version = "0.1.0"
description = ""
authors = ["The K-Boys"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
prophet = "^1.1.6"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
